version: '3.8'

services:

    micro_mail:
        build:
            args:
                user: leandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_mail
            - queue_micro_mail
        networks:
            - micromail

    queue_micro_mail:
        build:
            args:
                user: leandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        command: php artisan queue:work
        restart: unless-stopped
        volumes:
            - ./:/var/www
        ports:
            - "9002:9000"
        networks:
            - micromail

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - micromail

    redis_micro_mail:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6377:6379"
        networks:
            - micromail

networks:
    micromail:
        driver: bridge
